### ISSUE TITLE
KSP 1.2 Compatability

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/TestFlight#154]
Initial build against KSP 1.22  with updated ContractConfigurator shows only a few errors to address.

<img width="1032" alt="screen shot 2017-01-04 at 2 00 49 pm" src="https://cloud.githubusercontent.com/assets/161126/21660920/6b1ff98a-d286-11e6-8a97-17e489abf5e0.png">

**Comment by jwvanderbeck** [comment]
Looks like wheels are split up into a ton of separate modules now, which may mean some refactoring.  Bit of a pain but oh well.

**Comment by jwvanderbeck** [comment]
Fixed the panelStates issue.  Going to refactor the wheel failures since they no longer have a common base.

**Comment by jwvanderbeck** [comment]
Can't seem to find any information on the forum regarding changes to ModuleWheel

**Comment by linuxgurugamer** [comment]
I have a working and released version of TestFlight already, located here:https://github.com/linuxgurugamer/TestFlight

Please let me know if you would like me to discontinue it.  I took it up because it was very out-of-date, my release thread is here:  http://forum.kerbalspaceprogram.com/index.php?/topic/155934-12-test-flight-continued/

**Comment by jwvanderbeck** [comment]
Um well there already IS a released 1.2 version.
https://github.com/KSP-RO/TestFlight/releases/tag/1.8.0.0.beta-1

It just needs a bump to final if everything is ok, but no one reported back to me to say yay or nay.

Beyond that, I have to be honest I don't really appreciate a "continuation" being made since the entire point of it being here on Github as part of the RO project is that anyone can contribute directly to the project even if I am not around (though I do monitor Github and PRs, and jump in when I can to answer questions).

**Comment by linuxgurugamer** [comment]
I was requested by someone to get it updated, since it appeared (at that time) that it wasn't available.  I started it back in November when I got the request, but have kept it in a beta until the other day because I didn't know what the status of the RO version was.  I did make inquiries at the time, sorry if you missed them.
Anyway, I'll cancel my CKAN update for it, and will notify people that they should go back to your version.

I would suggest that you at least take a look at the 1.8 branch in my fork, just to see if there is anything I did which you might find useful.

**Comment by linuxgurugamer** [comment]
One thing. I'd like to put a link to the correct thread in my thread on the forum, but it looks like it was one of the deleted threads.  What should I use?

**Comment by jwvanderbeck** [comment]
It is fair to accuse me of not paying as much attention to it as I should, but that was why I made it open for others to contribute.  I just have other priorities in my life right now.

Basically all I did was get it working again in 1.2.  If you have additional work that you think should go in, please feel free to submit a PR.
